export interface ClinicType {
  slug: string
  name: string
  shortName: string
  headline: string
  subheadline: string
  intro: string
  complianceStandard: string
  complianceDetail: string
  keyNeeds: { title: string; detail: string }[]
  included: string[]
  zones: string[]
  cta: string
  metaTitle: string
  metaDescription: string
}

export const clinicTypes: ClinicType[] = [
  {
    slug: 'gp-practice',
    name: 'GP Practice Cleaning Adelaide',
    shortName: 'GP Practices',
    headline: 'RACGP-Compliant Cleaning for Adelaide GP Practices',
    subheadline: 'Documentation-led cleaning designed around RACGP accreditation',
    intro: 'General practices face regular RACGP accreditation reviews — and cleaning documentation is one of the most commonly flagged gaps. Zenith provides cleaning that is built from the ground up around RACGP GP4.1, with photo-documented checklists and monthly compliance reports that go straight into your accreditation file.',
    complianceStandard: 'RACGP GP4.1 — Standards for General Practices',
    complianceDetail: 'Our cleaning process directly supports RACGP Criterion C7.1 (Infection Prevention and Control). Every clean is documented with photos and a completed checklist — the exact records your accreditation reviewer will ask for.',
    keyNeeds: [
      { title: 'Consultation room disinfection', detail: 'Yellow-zone TGA-approved disinfection after every clean — compliant with RACGP GP4.1 infection control requirements.' },
      { title: 'Waiting room and reception', detail: 'Green-zone protocol for high-touch surfaces, seating, and front desk. Scheduled to avoid patient-hours disruption.' },
      { title: 'Patient toilets', detail: 'Dedicated red-zone equipment that never crosses into clinical areas. Documented on every visit.' },
      { title: 'Monthly compliance reports', detail: 'A documented cleaning file emailed monthly — ready for your next RACGP review without scrambling.' },
    ],
    included: [
      'RACGP GP4.1 colour-coded zone cleaning',
      'TGA-approved disinfectants in all clinical areas',
      'Photo-documented checklist after every clean',
      'Same team on every visit — no agency rotation',
      'After-hours scheduling to avoid patient disruption',
      'Monthly compliance report for your accreditation file',
      '24-hour redo guarantee if anything is missed',
    ],
    zones: ['Red (bathrooms)', 'Yellow (consultation & treatment rooms)', 'Green (reception, waiting, admin)', 'Blue (staff kitchen)'],
    cta: 'Book a free RACGP compliance walkthrough for your GP practice',
    metaTitle: 'GP Practice Cleaning Adelaide | RACGP GP4.1 Compliant',
    metaDescription: 'RACGP GP4.1 compliant cleaning for Adelaide GP practices. Photo-documented checklists, monthly compliance reports, and TGA-approved disinfection — audit-ready from day one.',
  },
  {
    slug: 'medical-centre',
    name: 'Medical Centre Cleaning Adelaide',
    shortName: 'Medical Centres',
    headline: "Medical Centre Cleaning for Adelaide's Busiest Practices",
    subheadline: 'Multi-room, high-volume cleaning with full RACGP compliance documentation',
    intro: 'Multi-GP medical centres have more rooms, more patients, and more compliance exposure than a single-GP practice. Zenith scales to match — same colour-coded zone system, same documentation standards, but scoped to the size and complexity of your centre.',
    complianceStandard: 'RACGP GP4.1 — Standards for General Practices',
    complianceDetail: 'Large medical centres typically have more complex zone layouts — multiple consultation suites, procedure rooms, and patient facilities. Our pre-clean walkthrough maps every room to the correct RACGP zone before your first clean.',
    keyNeeds: [
      { title: 'Multi-suite consultation rooms', detail: 'Each room documented individually. Yellow-zone protocol in every consultation and treatment space.' },
      { title: 'High-traffic waiting areas', detail: 'Frequent surface disinfection of high-touch areas — seats, door handles, reception counters.' },
      { title: 'Multiple patient bathrooms', detail: 'Dedicated red-zone equipment per bathroom cluster — no cross-contamination between facilities.' },
      { title: 'Complex scheduling', detail: "We work around your centre's extended hours, shift changeovers, and weekend schedules." },
    ],
    included: [
      'Full centre zone mapping before first clean',
      'RACGP GP4.1 compliant cleaning across all zones',
      'Individual room-level photo documentation',
      'Flexible scheduling for extended trading hours',
      'TGA-approved disinfectants throughout',
      'Monthly compliance report per centre',
      'Dedicated point of contact — not a call centre',
    ],
    zones: ['Red (all patient bathrooms)', 'Yellow (all consultation and procedure rooms)', 'Green (waiting, reception, admin, corridors)', 'Blue (staff kitchen and break rooms)'],
    cta: 'Book a free compliance walkthrough for your medical centre',
    metaTitle: 'Medical Centre Cleaning Adelaide | RACGP Compliant',
    metaDescription: 'Clinical cleaning for Adelaide medical centres. Multi-room RACGP GP4.1 compliant cleaning with photo documentation, zone mapping, and monthly compliance reports.',
  },
  {
    slug: 'specialist-clinic',
    name: 'Specialist Clinic Cleaning Adelaide',
    shortName: 'Specialist Clinics',
    headline: 'Specialist Clinic Cleaning Across Adelaide',
    subheadline: 'Cleaning calibrated to the specific infection-control needs of specialist practice',
    intro: "Specialist clinics — dermatology, cardiology, gastroenterology, ENT, ophthalmology, and others — often have procedure rooms that require higher-level disinfection protocols. Zenith's cleaning is built around these requirements, with TGA-approved products and colour-coded zone discipline that matches your clinical environment.",
    complianceStandard: 'RACGP GP4.1 and specialist accreditation standards',
    complianceDetail: 'Specialist clinics performing procedures operate under stricter infection control requirements. Our yellow and red zone protocols are calibrated to procedure room standards — not just general clinical cleaning.',
    keyNeeds: [
      { title: 'Procedure room cleaning', detail: 'High-level disinfection with TGA-approved products. Yellow-zone equipment dedicated to procedure spaces — documented on every clean.' },
      { title: 'Waiting room infection control', detail: 'Many specialist patients are immunocompromised. Green-zone protocols are executed with that higher-risk profile in mind.' },
      { title: 'Equipment surfaces', detail: 'Safe cleaning around specialist equipment. We follow manufacturer guidance and your infection control policy.' },
      { title: 'After-hours flexibility', detail: 'Most specialist clinics prefer cleaning outside patient hours. We schedule around you.' },
    ],
    included: [
      'Procedure room disinfection to specialist standards',
      'TGA-approved products throughout',
      'RACGP GP4.1 colour-coded zone cleaning',
      'Photo-documented compliance checklist',
      'After-hours scheduling',
      'Monthly compliance report',
      '12-month fixed rate — no price surprises',
    ],
    zones: ['Red (bathrooms)', 'Yellow (consultation, treatment, procedure rooms)', 'Green (waiting, reception, admin)', 'Blue (staff kitchen)'],
    cta: 'Book a free walkthrough for your specialist clinic',
    metaTitle: 'Specialist Clinic Cleaning Adelaide | Compliant Clinical Cleaning',
    metaDescription: 'RACGP-aligned cleaning for Adelaide specialist clinics — dermatology, cardiology, gastroenterology, ENT, and more. Procedure room disinfection, zone cleaning, full documentation.',
  },
  {
    slug: 'allied-health',
    name: 'Allied Health Clinic Cleaning Adelaide',
    shortName: 'Allied Health',
    headline: 'Cleaning for Allied Health Clinics in Adelaide',
    subheadline: 'Physio, chiro, psychology, OT, speech therapy — all covered',
    intro: 'Allied health clinics often share patients with GP practices and specialist services, making cross-contamination risk real. Zenith brings the same documentation-led cleaning standards used in GP practices to physiotherapy, chiropractic, psychology, occupational therapy, and speech therapy clinics across Adelaide.',
    complianceStandard: 'AHPRA registration standards and infection control best practice',
    complianceDetail: 'While allied health practices have different accreditation pathways to GPs, the infection control expectations from AHPRA and professional bodies align closely with RACGP GP4.1 principles. Our cleaning meets those expectations and provides the documentation to prove it.',
    keyNeeds: [
      { title: 'Treatment rooms', detail: 'Surface disinfection of treatment tables, benches, and equipment between sessions. Colour-coded equipment prevents cross-contamination.' },
      { title: 'High-contact waiting areas', detail: 'Thorough disinfection of seating, door handles, and shared surfaces in waiting rooms.' },
      { title: 'Accessible bathrooms', detail: 'Red-zone protocol for patient bathrooms — dedicated equipment, documented on every visit.' },
      { title: 'Flexible scheduling', detail: 'Allied health clinics often run appointment-only — we clean before opening or after close.' },
    ],
    included: [
      'Treatment room disinfection after every clean',
      'Colour-coded zone equipment throughout',
      'Photo-documented compliance checklist',
      'Flexible before/after-hours scheduling',
      'TGA-approved disinfectants',
      'Monthly service report',
      'Same cleaner on every visit',
    ],
    zones: ['Red (bathrooms)', 'Yellow (treatment rooms)', 'Green (waiting room, reception, admin)', 'Blue (staff kitchen)'],
    cta: 'Book a free walkthrough for your allied health clinic',
    metaTitle: 'Allied Health Clinic Cleaning Adelaide | Physio, Chiro, OT, Psychology',
    metaDescription: 'Professional cleaning for allied health clinics in Adelaide — physiotherapy, chiropractic, psychology, OT, and speech therapy. Documented, infection-control compliant, flexible scheduling.',
  },
  {
    slug: 'day-surgery',
    name: 'Day Surgery Cleaning Adelaide',
    shortName: 'Day Surgeries',
    headline: 'Day Surgery & Day Procedure Centre Cleaning in Adelaide',
    subheadline: 'High-level clinical cleaning for procedure and theatre environments',
    intro: 'Day surgeries and procedure centres operate under the strictest infection control requirements of any outpatient setting. Zenith provides high-level clinical cleaning calibrated to these environments — with thorough terminal cleaning protocols, dedicated zone equipment, and the documentation your accreditation requires.',
    complianceStandard: 'ACHS/NSQHS Standards and state health facility guidelines',
    complianceDetail: 'Day procedure centres are subject to NSQHS Standards accreditation. Our cleaning protocols meet the infection prevention and control requirements of Standard 3 (Preventing and Controlling Healthcare-Associated Infection), and provide the documentation records your surveyor will request.',
    keyNeeds: [
      { title: 'Theatre and procedure room terminal cleaning', detail: 'End-of-list terminal clean using TGA-approved hospital-grade disinfectants. Every surface documented.' },
      { title: 'Recovery room cleaning', detail: 'Between-patient surface disinfection of beds, monitors, and high-touch areas in recovery.' },
      { title: 'Sterile storage area cleaning', detail: 'Low-risk cleaning protocols around sterile supply storage — no risk of contamination.' },
      { title: 'Patient bathrooms', detail: 'Dedicated red-zone equipment. Cleaned and documented after every session.' },
    ],
    included: [
      'Theatre and procedure room terminal cleaning',
      'Hospital-grade TGA-approved disinfectants',
      'Between-patient and end-of-list cleaning protocols',
      'Recovery room disinfection',
      'Complete photo-documented checklists',
      'NSQHS Standard 3 aligned documentation',
      'Dedicated team — consistent protocols every time',
    ],
    zones: ['Red (patient bathrooms, sluice rooms)', 'Yellow (theatres, procedure rooms, recovery)', 'Green (waiting, admin, corridors)', 'Blue (staff kitchen and amenities)'],
    cta: 'Book a compliance walkthrough for your day surgery',
    metaTitle: 'Day Surgery Cleaning Adelaide | Theatre & Procedure Centre Cleaning',
    metaDescription: 'High-level clinical cleaning for Adelaide day surgeries and procedure centres. Terminal cleaning, hospital-grade disinfectants, NSQHS-aligned documentation.',
  },
  {
    slug: 'dental-clinic',
    name: 'Dental Clinic Cleaning Adelaide',
    shortName: 'Dental Clinics',
    headline: 'Dental Clinic Cleaning for Adelaide Practices',
    subheadline: 'Infection-control cleaning designed around the dental environment',
    intro: 'Dental practices face specific infection control challenges — aerosol-generating procedures, blood-borne pathogen exposure, and high surface contamination rates. Zenith provides cleaning that accounts for these realities, using TGA-approved disinfectants appropriate for dental environments and maintaining complete documentation records.',
    complianceStandard: 'ADA infection control guidelines and AHPRA standards',
    complianceDetail: "The Australian Dental Association's infection control guidelines set a high bar for environmental cleaning in dental practices. Our protocols align with these requirements, and our documentation gives you the paper trail your regulatory obligations demand.",
    keyNeeds: [
      { title: 'Surgery surface disinfection', detail: 'Dental chairs, lights, delivery units, and bracket tables cleaned with TGA-approved disinfectants after every session.' },
      { title: 'Aerosol-contaminated surfaces', detail: 'Thorough cleaning of all surfaces in procedure areas after aerosol-generating treatments — walls, cabinetry, and equipment.' },
      { title: 'Sterilisation room', detail: 'Safe cleaning around sterilisation equipment. Dedicated equipment, no cross-contamination risk.' },
      { title: 'Patient bathrooms', detail: 'Dedicated red-zone equipment. Cleaned and documented at every visit.' },
    ],
    included: [
      'Dental surgery disinfection with TGA-approved products',
      'Aerosol-aware surface cleaning protocols',
      'Colour-coded zone equipment throughout',
      'Photo-documented compliance checklist',
      'Sterilisation room environmental cleaning',
      'After-hours scheduling',
      'Monthly compliance documentation',
    ],
    zones: ['Red (patient bathrooms)', 'Yellow (dental surgeries, sterilisation room)', 'Green (waiting, reception, admin)', 'Blue (staff kitchen)'],
    cta: 'Book a free walkthrough for your dental practice',
    metaTitle: 'Dental Clinic Cleaning Adelaide | Infection Control Compliant',
    metaDescription: 'Professional dental clinic cleaning in Adelaide. TGA-approved disinfectants, aerosol-aware protocols, ADA infection control aligned, full compliance documentation.',
  },
  {
    slug: 'pathology',
    name: 'Pathology Collection Centre Cleaning Adelaide',
    shortName: 'Pathology Centres',
    headline: 'Pathology Collection Centre Cleaning in Adelaide',
    subheadline: 'Blood and specimen-aware cleaning with full zone compliance',
    intro: 'Pathology collection centres handle blood and biological specimens daily, making infection control critical. Zenith provides cleaning that respects the biohazard realities of collection environments — using appropriate disinfectants, dedicated zone equipment, and meticulous documentation.',
    complianceStandard: 'NATA accreditation standards and infection control best practice',
    complianceDetail: "NATA-accredited collection centres require documented environmental cleaning as part of their quality management system. Zenith's cleaning records provide exactly the evidence your quality auditor needs.",
    keyNeeds: [
      { title: 'Collection room disinfection', detail: 'Phlebotomy chairs, collection benches, and all high-touch surfaces cleaned with hospital-grade TGA-approved disinfectants.' },
      { title: 'Specimen reception area', detail: 'Safe environmental cleaning around specimen handling areas — dedicated equipment, appropriate disinfectant selection.' },
      { title: 'Patient waiting area', detail: 'Thorough green-zone cleaning of high-contact seating and surfaces in waiting areas.' },
      { title: 'Patient bathrooms', detail: 'Red-zone protocol with dedicated equipment — especially important in urine collection environments.' },
    ],
    included: [
      'Collection room disinfection with hospital-grade products',
      'Specimen area environmental cleaning',
      'Colour-coded zone equipment throughout',
      'Photo-documented compliance checklist',
      'NATA quality system aligned documentation',
      'Monthly compliance report',
      'Flexible scheduling around collection hours',
    ],
    zones: ['Red (bathrooms, specimen collection bathrooms)', 'Yellow (collection rooms, specimen reception)', 'Green (waiting, admin, reception)', 'Blue (staff kitchen)'],
    cta: 'Book a free walkthrough for your pathology collection centre',
    metaTitle: 'Pathology Collection Centre Cleaning Adelaide | NATA Compliant',
    metaDescription: 'Specialist cleaning for Adelaide pathology collection centres. Hospital-grade disinfectants, NATA quality system documentation, colour-coded zone compliance.',
  },
  {
    slug: 'radiology',
    name: 'Radiology & Imaging Centre Cleaning Adelaide',
    shortName: 'Radiology & Imaging',
    headline: 'Radiology & Medical Imaging Centre Cleaning in Adelaide',
    subheadline: 'Clinical cleaning built around imaging equipment and patient throughput',
    intro: 'Radiology and medical imaging centres present unique cleaning challenges — large, expensive imaging equipment, high patient throughput, and areas that require careful cleaning without interfering with sensitive equipment. Zenith brings clinical cleaning expertise to imaging environments across Adelaide.',
    complianceStandard: 'RACGP and state health guidelines for imaging facilities',
    complianceDetail: 'Imaging facilities often co-locate with or refer to GP and specialist services, and are expected to meet equivalent infection control standards. Our cleaning protocols and documentation support those expectations.',
    keyNeeds: [
      { title: 'Imaging room cleaning', detail: 'Safe environmental cleaning around MRI, CT, X-ray, and ultrasound equipment. We follow equipment manufacturer guidelines and your infection control policy.' },
      { title: 'Patient contact surfaces', detail: 'Disinfection of examination tables, pillows, and patient contact points between sessions.' },
      { title: 'Changing rooms and patient facilities', detail: 'Red and green zone protocols for patient bathrooms and change rooms.' },
      { title: 'High-traffic waiting areas', detail: 'Frequent disinfection of high-touch surfaces in waiting rooms with high patient turnover.' },
    ],
    included: [
      'Imaging room environmental cleaning',
      'Patient contact surface disinfection',
      'TGA-approved disinfectants throughout',
      'Colour-coded zone equipment',
      'Photo-documented compliance checklist',
      'Monthly compliance report',
      'Flexible scheduling around imaging sessions',
    ],
    zones: ['Red (patient bathrooms, change rooms)', 'Yellow (imaging rooms, examination areas)', 'Green (waiting, reception, admin)', 'Blue (staff kitchen)'],
    cta: 'Book a free walkthrough for your imaging centre',
    metaTitle: 'Radiology & Imaging Centre Cleaning Adelaide | Clinical Cleaning',
    metaDescription: 'Professional cleaning for Adelaide radiology and medical imaging centres. Safe around imaging equipment, TGA-approved disinfectants, full compliance documentation.',
  },
{
    slug: 'aged-care',
    name: 'Aged Care Facility Cleaning Adelaide',
    shortName: 'Aged Care',
    headline: 'Aged Care Facility Cleaning in Adelaide',
    subheadline: 'Infection-control cleaning for residential aged care and retirement living',
    intro: "Aged care facilities carry the highest infection-control stakes of any environment we service — vulnerable residents, communal living, and a regulator with real teeth. Zenith provides documented, infection-control cleaning for residential aged care facilities, day therapy centres and retirement living communities across Adelaide.",
    complianceStandard: 'Aged Care Quality Standards (ACQSC)',
    complianceDetail: "The Aged Care Quality and Safety Commission assesses whether your service environment is safe, clean and well-maintained — and outbreak management expectations post-COVID make documented environmental cleaning non-negotiable. Our records give you the evidence trail your quality assessors expect to see.",
    keyNeeds: [
      { title: 'Resident room and common area cleaning', detail: 'Scheduled cleaning of resident rooms, dining areas, lounges and corridors with TGA-approved products safe for continuous-occupancy environments.' },
      { title: 'Outbreak-ready protocols', detail: 'Enhanced cleaning procedures ready to activate during gastro or respiratory outbreaks — with the documentation the Commission asks for afterwards.' },
      { title: 'Bathroom and ensuite cleaning', detail: 'Red-zone protocol across shared bathrooms and resident ensuites — dedicated equipment, documented every clean.' },
      { title: 'Clinical and treatment areas', detail: 'Yellow-zone disinfection for treatment rooms, medication rooms and clinical storage areas.' },
    ],
    included: [
      'Cleaning aligned to Aged Care Quality Standards',
      'TGA-approved disinfectants throughout',
      'Outbreak cleaning protocols on standby',
      'Colour-coded zone equipment',
      'Photo-documented cleaning records',
      'Monthly documentation for quality assessors',
      'Police-checked, consistent cleaning team',
    ],
    zones: ['Red (bathrooms, ensuites, sluice rooms)', 'Yellow (treatment and medication rooms)', 'Green (resident rooms, lounges, dining, corridors)', 'Blue (kitchens and servery areas)'],
    cta: 'Book a walkthrough for your aged care facility',
    metaTitle: 'Aged Care Cleaning Adelaide | ACQSC Standards Aligned',
    metaDescription: 'Infection-control cleaning for Adelaide aged care facilities. Aligned to Aged Care Quality Standards, outbreak-ready protocols, full documentation for quality assessors.',
  },
  {
    slug: 'pharmacy',
    name: 'Pharmacy Cleaning Adelaide',
    shortName: 'Pharmacies',
    headline: 'Pharmacy Cleaning in Adelaide',
    subheadline: 'Documented cleaning for community pharmacies and compounding practices',
    intro: "Community pharmacies sit in a unique position — retail floor at the front, dispensary and consulting rooms behind, and QCPP accreditation expectations across all of it. Zenith cleans Adelaide pharmacies with the zone discipline and documentation that quality accreditation requires.",
    complianceStandard: 'QCPP — Quality Care Pharmacy Program',
    complianceDetail: "QCPP accreditation includes requirements around premises presentation, cleanliness and infection control — particularly for pharmacies offering vaccinations, wound care or health screening services. Our documented cleans support your QCPP evidence requirements.",
    keyNeeds: [
      { title: 'Dispensary cleaning', detail: 'Careful cleaning around dispensing benches, shelving and storage — dust-free without disturbing stock or workflows.' },
      { title: 'Consulting and vaccination rooms', detail: 'Clinical-grade disinfection for rooms used for vaccinations, blood pressure checks and health services — yellow-zone protocol as standard.' },
      { title: 'Retail floor presentation', detail: 'Floors, shelving lines and entry glass maintained to retail standard — presentation sells in pharmacy.' },
      { title: 'Staff and customer facilities', detail: 'Red-zone protocol for bathrooms, blue-zone for staff kitchens — never crossing into dispensary or clinical areas.' },
    ],
    included: [
      'QCPP-aligned cleaning documentation',
      'Clinical-grade disinfection in service rooms',
      'TGA-approved products throughout',
      'Colour-coded zone equipment',
      'After-hours cleaning — no trading disruption',
      'Photo-documented checklist every clean',
      'Monthly compliance summary',
    ],
    zones: ['Red (customer and staff bathrooms)', 'Yellow (consulting and vaccination rooms)', 'Green (retail floor, dispensary, storage)', 'Blue (staff kitchen)'],
    cta: 'Book a walkthrough for your pharmacy',
    metaTitle: 'Pharmacy Cleaning Adelaide | QCPP Aligned',
    metaDescription: 'Professional pharmacy cleaning in Adelaide — dispensary, consulting rooms and retail floor. QCPP-aligned documentation, after-hours scheduling.',
  },
  {
    slug: 'veterinary',
    name: 'Veterinary Clinic Cleaning Adelaide',
    shortName: 'Veterinary Clinics',
    headline: 'Veterinary Clinic Cleaning in Adelaide',
    subheadline: 'Animal-safe, infection-control cleaning for vet practices and animal hospitals',
    intro: "Veterinary clinics fight a two-front battle: genuine infection control — parvo, cat flu and zoonotic risks are not theoretical — and the hair, dander and odour load that no office cleaner is equipped for. Zenith cleans Adelaide vet practices with animal-safe products and the same zone discipline we bring to human healthcare.",
    complianceStandard: 'Veterinary premises standards and ASAV accreditation',
    complianceDetail: "South Australian veterinary premises standards and ASAV hospital accreditation both set expectations for hygiene, biosecurity and premises maintenance. Our documented cleaning supports those requirements — and gives practice owners evidence their biosecurity protocols are actually being followed overnight.",
    keyNeeds: [
      { title: 'Consult and treatment room disinfection', detail: 'Veterinary-appropriate disinfectants effective against parvovirus and common pathogens — applied at correct contact times, safe for animal contact once dry.' },
      { title: 'Kennel and cattery areas', detail: 'Cleaning protocols for housing areas that respect isolation zones — equipment never moves from isolation to general wards.' },
      { title: 'Surgery and prep areas', detail: 'Theatre-grade cleaning for surgical suites, prep benches and recovery areas.' },
      { title: 'Hair, dander and odour control', detail: 'The load a vet clinic generates daily needs commercial-grade extraction and floor care — built into the standard scope, not an extra.' },
    ],
    included: [
      'Animal-safe, veterinary-appropriate disinfectants',
      'Isolation-aware zone protocols',
      'Surgery and treatment area disinfection',
      'Hair and dander extraction as standard',
      'After-hours cleaning around boarding animals',
      'Photo-documented checklist every clean',
      'Consistent team familiar with your biosecurity rules',
    ],
    zones: ['Red (bathrooms, isolation wards)', 'Yellow (consult rooms, surgery, treatment)', 'Green (reception, waiting, retail, offices)', 'Blue (staff kitchen and food prep)'],
    cta: 'Book a walkthrough for your veterinary clinic',
    metaTitle: 'Vet Clinic Cleaning Adelaide | Animal-Safe & Documented',
    metaDescription: 'Veterinary clinic cleaning in Adelaide — animal-safe disinfectants, isolation-aware protocols, surgery-grade cleaning. Documented every visit.',
  },
]

export function getClinicBySlug(slug: string): ClinicType | undefined {
  return clinicTypes.find(c => c.slug === slug)
}
