export interface Location {
  slug: string
  suburb: string
  region: string
  headline: string
  intro: string
  localContext: string
  nearbyAreas: string[]
  metaTitle: string
  metaDescription: string
}

export const locations: Location[] = [
  {
    slug: 'adelaide-cbd',
    suburb: 'Adelaide CBD',
    region: 'City of Adelaide',
    headline: 'Medical Cleaning in Adelaide CBD',
    intro: 'The Adelaide CBD holds the densest concentration of medical practices in South Australia — specialist suites on North Terrace, GP clinics around Hindmarsh Square, and consulting rooms clustered near the Royal Adelaide Hospital and Calvary Adelaide. Zenith provides RACGP GP4.1 compliant cleaning for CBD practices, scheduled after hours to work around city parking and patient flow.',
    localContext: 'We service medical suites and clinics throughout the CBD grid — from North Terrace medical chambers to Pulteney Street consulting rooms. After-hours access, building security protocols, and loading zone timing are all handled as part of onboarding.',
    nearbyAreas: ['North Adelaide', 'Kent Town', 'Wayville', 'Mile End'],
    metaTitle: 'Medical Cleaning Adelaide CBD | RACGP Compliant',
    metaDescription: 'RACGP GP4.1 compliant medical cleaning for Adelaide CBD practices — specialist suites, GP clinics, and consulting rooms. After-hours scheduling, photo-documented compliance.',
  },
  {
    slug: 'north-adelaide',
    suburb: 'North Adelaide',
    region: 'City of Adelaide',
    headline: 'Medical Cleaning in North Adelaide',
    intro: 'North Adelaide is home to one of Adelaide\'s most established medical precincts — specialist consulting rooms along Melbourne Street and Ward Street, and practices serving Calvary North Adelaide Hospital and the Women\'s and Children\'s Hospital nearby. Zenith provides compliant clinical cleaning matched to the standards these practices operate under.',
    localContext: 'Many North Adelaide practices operate in converted heritage buildings, which bring their own cleaning considerations — varied floor surfaces, older bathroom facilities, and non-standard layouts. Our pre-clean walkthrough maps each space into the correct RACGP zone regardless of building age.',
    nearbyAreas: ['Adelaide CBD', 'Prospect', 'Medindie', 'Walkerville'],
    metaTitle: 'Medical Cleaning North Adelaide | RACGP Compliant',
    metaDescription: 'Clinical cleaning for North Adelaide medical practices and specialist rooms. RACGP GP4.1 compliant, photo-documented, servicing the Melbourne Street medical precinct.',
  },
  {
    slug: 'norwood',
    suburb: 'Norwood',
    region: 'Eastern Suburbs',
    headline: 'Medical Cleaning in Norwood',
    intro: 'Norwood and the surrounding eastern suburbs carry a strong mix of GP practices, allied health clinics, and specialist rooms along The Parade and Magill Road. Zenith services eastern-suburbs practices with RACGP GP4.1 compliant cleaning, after-hours scheduling, and complete compliance documentation.',
    localContext: 'The Parade precinct mixes medical suites with retail frontage, which means shared entrances and strata common areas. We coordinate with building management where needed and keep clinical zones fully separated from common-area cleaning.',
    nearbyAreas: ['Kent Town', 'St Peters', 'Magill', 'Burnside'],
    metaTitle: 'Medical Cleaning Norwood | Eastern Suburbs Adelaide',
    metaDescription: 'RACGP compliant medical and allied health cleaning in Norwood and Adelaide\'s eastern suburbs. Photo-documented cleans, after-hours scheduling, dedicated team.',
  },
  {
    slug: 'unley',
    suburb: 'Unley',
    region: 'Inner South',
    headline: 'Medical Cleaning in Unley',
    intro: 'Unley Road and King William Road host a dense strip of GP practices, dental clinics, physiotherapy and allied health rooms serving Adelaide\'s inner south. Zenith provides documented, RACGP-compliant cleaning for practices from Parkside through to Malvern.',
    localContext: 'Inner-south practices often run extended evening hours for after-work appointments. We schedule cleans after your last patient — often 8pm or later — so the practice opens spotless without a cleaner ever crossing paths with a patient.',
    nearbyAreas: ['Parkside', 'Malvern', 'Goodwood', 'Fullarton'],
    metaTitle: 'Medical Cleaning Unley | Inner South Adelaide',
    metaDescription: 'Medical, dental and allied health cleaning in Unley and Adelaide\'s inner south. RACGP GP4.1 compliant with photo documentation and late-evening scheduling.',
  },
  {
    slug: 'prospect',
    suburb: 'Prospect',
    region: 'Inner North',
    headline: 'Medical Cleaning in Prospect',
    intro: 'Prospect Road carries one of the inner north\'s busiest medical strips — GP clinics, dental practices, and allied health rooms serving communities from Blair Athol to Fitzroy. Zenith brings RACGP GP4.1 compliant cleaning with full photo documentation to inner-north practices.',
    localContext: 'Many Prospect-area clinics are high-throughput bulk-billing practices where waiting room turnover is constant. Our green-zone protocols put extra weight on high-touch surfaces — seating, counters, door hardware — cleaned and documented every visit.',
    nearbyAreas: ['North Adelaide', 'Blair Athol', 'Sefton Park', 'Walkerville'],
    metaTitle: 'Medical Cleaning Prospect | Inner North Adelaide',
    metaDescription: 'RACGP compliant cleaning for GP, dental and allied health practices in Prospect and Adelaide\'s inner north. Documented cleans, high-touch surface focus.',
  },
  {
    slug: 'glenelg',
    suburb: 'Glenelg',
    region: 'Western Beaches',
    headline: 'Medical Cleaning in Glenelg',
    intro: 'Glenelg and the Holdfast Bay area support a broad mix of GP practices, specialist rooms and allied health clinics along Jetty Road and Brighton Road. Zenith services beachside practices with the same RACGP GP4.1 compliant cleaning standard we bring to every Adelaide clinic.',
    localContext: 'Coastal practices deal with sand and salt tracked through entrances year-round — entry zones and waiting areas need more frequent hard-floor attention than inland clinics. We build that into the scope rather than treating it as an extra.',
    nearbyAreas: ['Brighton', 'Somerton Park', 'Plympton', 'Morphettville'],
    metaTitle: 'Medical Cleaning Glenelg | Holdfast Bay Adelaide',
    metaDescription: 'Medical and allied health cleaning in Glenelg and Holdfast Bay. RACGP GP4.1 compliant, photo-documented, scheduled around your practice hours.',
  },
  {
    slug: 'marion',
    suburb: 'Marion',
    region: 'Southern Suburbs',
    headline: 'Medical Cleaning in Marion',
    intro: 'The Marion precinct — anchored by Westfield Marion and the SA Aquatic Centre corridor — hosts large medical centres, day surgeries and specialist clinics serving Adelaide\'s south. Zenith provides compliance-grade cleaning scaled for multi-room, high-volume southern practices.',
    localContext: 'Southern medical centres are often the largest-format practices we service — multiple GP suites, on-site pathology collection, and allied health under one roof. Our zone mapping covers mixed-use medical buildings room by room, with separate documentation per tenancy where needed.',
    nearbyAreas: ['Oaklands Park', 'Warradale', 'Sturt', 'Bedford Park'],
    metaTitle: 'Medical Cleaning Marion | Southern Adelaide',
    metaDescription: 'Medical centre and clinic cleaning in Marion and southern Adelaide. RACGP GP4.1 compliant, multi-room zone mapping, monthly compliance reporting.',
  },
  {
    slug: 'bedford-park',
    suburb: 'Bedford Park',
    region: 'Southern Suburbs',
    headline: 'Medical Cleaning in Bedford Park',
    intro: 'Bedford Park sits at the heart of Adelaide\'s southern health precinct — Flinders Medical Centre, Flinders Private Hospital, and the surrounding cluster of specialist suites and consulting rooms. Zenith provides clinical cleaning for the private practices and specialist clinics operating around the Flinders precinct.',
    localContext: 'Practices near a major teaching hospital are typically specialist-heavy — procedure rooms, day-surgery referrals, and immunocompromised patient loads. Our yellow-zone protocols run at procedure-room standard here, with TGA-approved hospital-grade disinfectants as the default.',
    nearbyAreas: ['Flinders Park precinct', 'St Marys', 'Pasadena', 'Marion'],
    metaTitle: 'Medical Cleaning Bedford Park | Flinders Precinct',
    metaDescription: 'Specialist and clinical cleaning near the Flinders medical precinct, Bedford Park. Procedure-room standard disinfection, RACGP compliant, fully documented.',
  },
  {
    slug: 'modbury',
    suburb: 'Modbury',
    region: 'North East',
    headline: 'Medical Cleaning in Modbury',
    intro: 'Modbury anchors Adelaide\'s north-eastern health corridor — Modbury Hospital, the surrounding GP practices, and the clinic clusters through Tea Tree Gully and Golden Grove. Zenith services north-east practices with RACGP GP4.1 compliant cleaning and complete audit documentation.',
    localContext: 'The north-east corridor is growth territory — new clinics opening in retail precincts and converted commercial spaces. New fit-outs still need correct zone classification from day one; we do that mapping as part of the free walkthrough before your first clean.',
    nearbyAreas: ['Tea Tree Gully', 'Golden Grove', 'St Agnes', 'Ridgehaven'],
    metaTitle: 'Medical Cleaning Modbury | North East Adelaide',
    metaDescription: 'RACGP compliant medical cleaning in Modbury, Tea Tree Gully and Adelaide\'s north east. Zone-mapped cleans, photo documentation, monthly compliance reports.',
  },
  {
    slug: 'salisbury',
    suburb: 'Salisbury',
    region: 'Northern Suburbs',
    headline: 'Medical Cleaning in Salisbury',
    intro: 'Salisbury and Adelaide\'s northern corridor — through Mawson Lakes, Parafield Gardens and Elizabeth — carry some of the state\'s busiest bulk-billing practices and community health clinics. Zenith brings documented, RACGP-compliant cleaning to northern practices at rates built for high-volume clinics.',
    localContext: 'High-throughput northern clinics see patient volumes that put serious load on waiting rooms and patient bathrooms. Our red and green zone rotations are weighted accordingly, and every clean is photo-documented so your compliance file keeps pace with your patient numbers.',
    nearbyAreas: ['Mawson Lakes', 'Parafield Gardens', 'Elizabeth', 'Paralowie'],
    metaTitle: 'Medical Cleaning Salisbury | Northern Adelaide',
    metaDescription: 'Medical and clinic cleaning in Salisbury and Adelaide\'s north. RACGP GP4.1 compliant, built for high-volume bulk-billing practices, fully documented.',
  },
  {
    slug: 'port-adelaide',
    suburb: 'Port Adelaide',
    region: 'Western Suburbs',
    headline: 'Medical Cleaning in Port Adelaide',
    intro: 'Port Adelaide and the western corridor — through Semaphore, West Lakes and Woodville — support a wide network of GP practices, allied health clinics and community health services. Zenith provides RACGP GP4.1 compliant cleaning across Adelaide\'s west with after-hours scheduling and full documentation.',
    localContext: 'Western-suburbs practices range from heritage-building GP clinics in the Port centre to modern medical centres at West Lakes. Whatever the building, the zone system is the same — and so is the documentation your accreditation review will ask for.',
    nearbyAreas: ['Semaphore', 'West Lakes', 'Woodville', 'Findon'],
    metaTitle: 'Medical Cleaning Port Adelaide | Western Suburbs',
    metaDescription: 'RACGP compliant medical cleaning in Port Adelaide and Adelaide\'s western suburbs. GP, allied health and community clinics — documented, after-hours, dedicated team.',
  },
  {
    slug: 'burnside',
    suburb: 'Burnside',
    region: 'Eastern Suburbs',
    headline: 'Medical Cleaning in Burnside',
    intro: 'The Burnside area — including the specialist rooms around Burnside War Memorial Hospital and the clinic strips along Greenhill and Portrush Roads — hosts many of Adelaide\'s private specialist practices. Zenith provides clinical cleaning calibrated to specialist standards, with the documentation private practices need.',
    localContext: 'Specialist practices in the east typically run smaller footprints with higher fit-out standards — and expect cleaning to match. Our teams work to a documented room-by-room scope, with the same cleaner assigned to your practice every visit.',
    nearbyAreas: ['Toorak Gardens', 'Tusmore', 'Glenside', 'Norwood'],
    metaTitle: 'Medical Cleaning Burnside | Eastern Adelaide Specialists',
    metaDescription: 'Specialist clinic and medical cleaning in Burnside and Adelaide\'s east. RACGP compliant, procedure-room capable, photo-documented every visit.',
  },
  {
    slug: 'mawson-lakes',
    suburb: 'Mawson Lakes',
    region: 'Northern Suburbs',
    headline: 'Medical Cleaning in Mawson Lakes',
    intro: 'Mawson Lakes is one of Adelaide\'s fastest-growing medical service hubs — modern GP clinics, dental practices and allied health rooms serving the technology precinct and surrounding residential growth. Zenith provides RACGP GP4.1 compliant cleaning for the new generation of northern practices.',
    localContext: 'Most Mawson Lakes clinics operate from modern purpose-built tenancies — which makes zone classification straightforward, but raises expectations on presentation. Our documented cleans keep modern fit-outs looking the way they did at handover.',
    nearbyAreas: ['Salisbury', 'Parafield', 'Pooraka', 'Greenfields'],
    metaTitle: 'Medical Cleaning Mawson Lakes | Northern Adelaide',
    metaDescription: 'Medical, dental and allied health cleaning in Mawson Lakes. RACGP GP4.1 compliant cleaning for modern practices — documented, scheduled around you.',
  },
{
    slug: 'gawler',
    suburb: 'Gawler',
    region: 'Northern Corridor',
    headline: 'Medical Cleaning in Gawler',
    intro: "Gawler anchors the health services of Adelaide's outer north — the Gawler Health Service, the GP practices along Murray Street, and the clinics serving the fast-growing corridor through Evanston and Hewett. Zenith brings the same RACGP GP4.1 compliant cleaning standard to Gawler practices as we deliver across metropolitan Adelaide.",
    localContext: "Outer-corridor practices often struggle to find cleaners who will take compliance documentation seriously at a workable price. Because we cluster our northern runs, Gawler practices get metro-standard service — photo-documented cleans, monthly compliance reports — without a regional premium.",
    nearbyAreas: ['Evanston', 'Willaston', 'Hewett', 'Munno Para'],
    metaTitle: 'Medical Cleaning Gawler | RACGP Compliant',
    metaDescription: "RACGP GP4.1 compliant medical cleaning in Gawler and Adelaide's outer north. Photo-documented cleans, monthly compliance reports, metro-standard service.",
  },
  {
    slug: 'elizabeth',
    suburb: 'Elizabeth',
    region: 'Northern Suburbs',
    headline: 'Medical Cleaning in Elizabeth',
    intro: "Elizabeth and the Playford area centre on the Lyell McEwin Hospital precinct — one of Adelaide's busiest public health hubs — surrounded by high-volume GP practices, community health services and specialist clinics. Zenith provides documented, RACGP-compliant cleaning built for the patient volumes northern practices handle.",
    localContext: "Practices around the Lyell McEwin precinct run some of the highest patient throughput in the state. Waiting rooms and patient bathrooms take the load — our red and green zone rotations are weighted for it, and every clean is photo-documented.",
    nearbyAreas: ['Elizabeth Vale', 'Smithfield', 'Davoren Park', 'Salisbury'],
    metaTitle: 'Medical Cleaning Elizabeth | Lyell McEwin Precinct',
    metaDescription: 'Medical and clinic cleaning in Elizabeth and the Playford area. RACGP GP4.1 compliant, built for high-volume practices near the Lyell McEwin precinct.',
  },
  {
    slug: 'noarlunga',
    suburb: 'Noarlunga',
    region: 'Outer South',
    headline: 'Medical Cleaning in Noarlunga',
    intro: "The Noarlunga precinct — anchored by Noarlunga Hospital and the GP Plus Health Care Centre — serves Adelaide's entire outer south, from Christies Beach through Morphett Vale to Hackham. Zenith services southern practices with RACGP GP4.1 compliant cleaning and complete audit documentation.",
    localContext: "The outer south mixes large purpose-built medical centres at Noarlunga Centre with smaller suburban GP and allied health clinics through Morphett Vale and Christies Beach. Our zone mapping scales to both — the documentation standard stays identical.",
    nearbyAreas: ['Christies Beach', 'Morphett Vale', 'Hackham', 'Port Noarlunga'],
    metaTitle: 'Medical Cleaning Noarlunga | Outer South Adelaide',
    metaDescription: "RACGP compliant medical cleaning in Noarlunga, Christies Beach and Adelaide's outer south. Zone-mapped, photo-documented, after-hours scheduling.",
  },
  {
    slug: 'seaford-aldinga',
    suburb: 'Seaford & Aldinga',
    region: 'Southern Beaches',
    headline: 'Medical Cleaning in Seaford & Aldinga',
    intro: "The southern beaches corridor — Seaford, Moana, Aldinga and Sellicks — is one of Adelaide's fastest-growing residential belts, and its GP practices, dental clinics and allied health rooms are growing with it. Zenith brings compliant, documented cleaning to southern-beaches practices as part of our regular southern runs.",
    localContext: "Newer practices in growth suburbs are often working toward their first RACGP accreditation review. Our free walkthrough maps your rooms into the colour-zone system and hands you a written gap report — a head start on the compliance file before the reviewer ever books in.",
    nearbyAreas: ['Moana', 'Port Willunga', 'Sellicks Beach', 'McLaren Vale'],
    metaTitle: 'Medical Cleaning Seaford & Aldinga | Southern Beaches',
    metaDescription: 'Medical, dental and allied health cleaning in Seaford, Aldinga and the southern beaches. RACGP GP4.1 compliant with full photo documentation.',
  },
  {
    slug: 'mclaren-vale',
    suburb: 'McLaren Vale',
    region: 'Fleurieu Peninsula',
    headline: 'Medical Cleaning in McLaren Vale',
    intro: "McLaren Vale and the northern Fleurieu — including Willunga and McLaren Flat — are served by a tight network of GP practices and allied health clinics that carry the health load for a large semi-rural population. Zenith services Fleurieu practices on scheduled runs with the same compliance documentation we provide metro clinics.",
    localContext: "Semi-rural practices can't afford a cleaner who no-shows — there's no backup crew around the corner. Our scheduled-run model and dedicated-team policy mean the same people arrive on the same nights, every week, documented every visit.",
    nearbyAreas: ['Willunga', 'McLaren Flat', 'Old Noarlunga', 'Aldinga'],
    metaTitle: 'Medical Cleaning McLaren Vale | Fleurieu Peninsula',
    metaDescription: 'RACGP compliant medical cleaning in McLaren Vale, Willunga and the northern Fleurieu. Reliable scheduled runs, photo-documented compliance.',
  },
  {
    slug: 'mount-barker',
    suburb: 'Mount Barker',
    region: 'Adelaide Hills',
    headline: 'Medical Cleaning in Mount Barker',
    intro: "Mount Barker is the fastest-growing regional centre in South Australia — and its medical infrastructure is expanding to match, from the Mount Barker District Soldiers' Memorial Hospital to the new clinics opening across the district. Zenith provides RACGP GP4.1 compliant cleaning for Hills practices on regular scheduled runs.",
    localContext: "New clinics are opening in Mount Barker faster than anywhere else in the state, and new fit-outs need correct zone classification from day one. We do that mapping in the free walkthrough — before your first clean, not after your first audit finding.",
    nearbyAreas: ['Littlehampton', 'Nairne', 'Hahndorf', 'Strathalbyn'],
    metaTitle: 'Medical Cleaning Mount Barker | Adelaide Hills',
    metaDescription: 'Medical and clinic cleaning in Mount Barker and the Adelaide Hills. RACGP GP4.1 compliant, zone-mapped from day one, photo-documented.',
  },
  {
    slug: 'stirling',
    suburb: 'Stirling',
    region: 'Adelaide Hills',
    headline: 'Medical Cleaning in Stirling',
    intro: "Stirling and the central Hills — Aldgate, Bridgewater, Crafers — support an established network of GP practices, dental and allied health clinics serving the Hills community. Zenith services central-Hills practices with documented, RACGP-compliant cleaning on scheduled evening runs.",
    localContext: "Hills practices often operate from character buildings with timber floors, older wet areas and non-standard layouts. The zone system adapts to the building — red-zone equipment stays dedicated to bathrooms whether they're new or heritage — and the documentation looks the same to your accreditation reviewer either way.",
    nearbyAreas: ['Aldgate', 'Bridgewater', 'Crafers', 'Hahndorf'],
    metaTitle: 'Medical Cleaning Stirling | Central Adelaide Hills',
    metaDescription: 'RACGP compliant medical cleaning in Stirling, Aldgate and the central Adelaide Hills. Documented cleans, dedicated team, evening scheduling.',
  },
  {
    slug: 'victor-harbor',
    suburb: 'Victor Harbor',
    region: 'Fleurieu Peninsula',
    headline: 'Medical Cleaning in Victor Harbor',
    intro: "Victor Harbor and the southern Fleurieu — including Goolwa and Port Elliot — carry a large retiree population and the GP practices, specialist visiting rooms and allied health clinics that serve it. Zenith brings metro-standard compliance cleaning to south-coast practices on scheduled runs.",
    localContext: "Practices with older patient demographics run higher infection-control stakes — more immunocompromised patients, more chronic disease clinics, more visiting specialist sessions. Our TGA-approved product standard and documented zone discipline are built for exactly that risk profile.",
    nearbyAreas: ['Goolwa', 'Port Elliot', 'Middleton', 'Encounter Bay'],
    metaTitle: 'Medical Cleaning Victor Harbor | South Coast',
    metaDescription: 'RACGP compliant medical cleaning in Victor Harbor, Goolwa and the southern Fleurieu. Metro-standard documentation, scheduled south-coast runs.',
  },
  {
    slug: 'murray-bridge',
    suburb: 'Murray Bridge',
    region: 'Murraylands',
    headline: 'Medical Cleaning in Murray Bridge',
    intro: "Murray Bridge is the health hub of the Murraylands — the Murray Bridge Soldiers' Memorial Hospital, the Bridge Clinic network, and the GP and allied health practices serving the wider river region. Zenith services Murray Bridge practices with RACGP GP4.1 compliant cleaning and full audit documentation.",
    localContext: "Regional hub practices serve patients who travel long distances, which concentrates volume into fewer, busier clinics. Waiting areas and patient facilities work harder here — our cleaning scope and documentation are weighted to match.",
    nearbyAreas: ['Tailem Bend', 'Mannum', 'Callington', 'Strathalbyn'],
    metaTitle: 'Medical Cleaning Murray Bridge | Murraylands',
    metaDescription: 'Medical and clinic cleaning in Murray Bridge and the Murraylands. RACGP GP4.1 compliant, photo-documented, servicing the regional health hub.',
  },
  {
    slug: 'barossa-valley',
    suburb: 'Barossa Valley',
    region: 'Barossa',
    headline: 'Medical Cleaning in the Barossa Valley',
    intro: "The Barossa — Tanunda, Nuriootpa and Angaston — is served by a close-knit network of GP practices and allied health clinics alongside the Barossa Hills Fleurieu health services. Zenith brings documented, RACGP-compliant cleaning to Barossa practices on scheduled northern runs.",
    localContext: "Like most regional clinic networks, Barossa practices need a cleaning partner who shows up reliably and keeps the compliance paperwork tight without hand-holding. Our dedicated-team model and monthly compliance reports are built for practices that don't have time to manage their cleaner.",
    nearbyAreas: ['Tanunda', 'Nuriootpa', 'Angaston', 'Lyndoch'],
    metaTitle: 'Medical Cleaning Barossa Valley | Tanunda & Nuriootpa',
    metaDescription: 'RACGP compliant medical cleaning in the Barossa Valley — Tanunda, Nuriootpa, Angaston. Reliable scheduled runs, full compliance documentation.',
  },
]

export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find(l => l.slug === slug)
}
